# Configuração do Modelo de Previsão de Vendas - Hackathon 2025

general:
  project_name: "hackathon-forecast-model"
  random_seed: 42
  n_jobs: -1
  verbose: true

data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  features_path: "data/features/"
  
  aggregation:
    frequency: "W"  # Semanal
    start_date: "2022-01-01"
    end_date: "2022-12-31"
  
  missing_data:
    numeric_strategy: "median"
    categorical_strategy: "mode"
    time_series_strategy: "forward_fill"

features:
  temporal:
    include_week_of_year: true
    include_month: true
    include_quarter: true
    include_seasonality: true
    include_holidays: true
  
  lag:
    periods: [1, 2, 4, 8]
    rolling_windows: [4, 8, 12]
    include_growth_rate: true
  
  categorical:
    encoding_method: "target"  # ou "onehot", "label"
    min_category_size: 10
  
  selection:
    method: "rfe"  # ou "selectkbest", "correlation"
    max_features: 50
    correlation_threshold: 0.95

# Configurações dos Modelos
models:
  xgboost:
    n_estimators: 1000
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    early_stopping_rounds: 50
    eval_metric: "mae"
  
  lightgbm:
    n_estimators: 1000
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    early_stopping_rounds: 50
    metric: "mae"
    verbose: -1
  
  prophet:
    seasonality_mode: "multiplicative"
    yearly_seasonality: true
    weekly_seasonality: true
    daily_seasonality: false
    changepoint_prior_scale: 0.05
    seasonality_prior_scale: 10.0
  
  ensemble:
    method: "weighted_average"  # ou "stacking"
    weights:
      xgboost: 0.4
      lightgbm: 0.4
      prophet: 0.2

# Configurações de Ensemble
ensemble:
  weighted:
    enabled: true
    optimize_weights: true
    optimization_trials: 200
    optimization_timeout: 1800  # segundos
  
  stacking:
    enabled: true
    meta_learner: "ridge"  # "ridge", "linear", "random_forest"
    ridge_alpha: 1.0
    rf_n_estimators: 100
    rf_max_depth: 5
  
  validation:
    diversity_threshold: 0.7  # Correlação máxima entre modelos
    stability_bootstrap: 100
    min_improvement: 0.01  # Melhoria mínima sobre melhor modelo individual

validation:
  method: "time_series_split"
  n_splits: 5
  test_size: 4  # semanas
  gap: 0  # semanas entre treino e teste
  
  metrics:
    - "wmape"
    - "mae"
    - "rmse"
    - "mape"

hyperparameter_tuning:
  enabled: true
  method: "optuna"
  n_trials: 100
  timeout: 3600  # segundos
  
  search_space:
    xgboost:
      n_estimators: [500, 2000]
      max_depth: [3, 10]
      learning_rate: [0.01, 0.3]
      subsample: [0.6, 1.0]
      colsample_bytree: [0.6, 1.0]
    
    lightgbm:
      n_estimators: [500, 2000]
      max_depth: [3, 10]
      learning_rate: [0.01, 0.3]
      subsample: [0.6, 1.0]
      colsample_bytree: [0.6, 1.0]

prediction:
  target_weeks: [1, 2, 3, 4, 5]  # Semanas de janeiro/2023
  post_processing:
    ensure_positive: true
    apply_bounds: true
    max_multiplier: 3.0  # Máximo 3x a média histórica

# Configurações de Formatação de Saída
output:
  # Configurações CSV
  csv_separator: ";"
  csv_encoding: "utf-8"
  csv_decimal: "."
  
  # Configurações Parquet
  parquet_compression: "snappy"
  
  # Configurações de Validação
  validate_format: true
  add_timestamp: true
  
  # Formatos de arquivo
  default_format: "csv"  # "csv" ou "parquet"
  filename_template: "submission_{timestamp}"

experiment_tracking:
  enabled: true
  backend: "mlflow"  # ou "wandb"
  experiment_name: "hackathon-forecast-2025"
  
  artifacts:
    - "model"
    - "features"
    - "predictions"
    - "metrics"
    - "plots"

performance:
  use_polars: true
  chunk_size: 10000
  parallel_processing: true
  cache_features: true
  
  memory:
    low_memory_mode: false
    dtype_optimization: true

# Configurações de Otimização de Performance
optimization:
  # Configurações gerais
  enabled: true
  use_polars: true
  use_caching: true
  use_parallel: true
  
  # Configurações de memória
  memory_limit_gb: 8.0
  optimize_dtypes: true
  force_gc: true
  
  # Configurações de paralelização
  max_workers: null  # null = auto-detect CPU cores
  batch_size: 10000
  
  # Configurações de cache
  cache_dir: "data/features/cache"
  cache_features: true
  cache_models: true
  
  # Configurações específicas por componente
  data_loading:
    use_lazy_loading: true
    chunk_size: 100000
    parallel_loading: true
  
  feature_engineering:
    parallel_features: true
    cache_intermediate: true
    use_polars_ops: true
  
  prediction:
    batch_prediction: true
    streaming_output: false
    optimize_memory: true